### ISSUE TITLE
Can't find node command (ST3)

### ISSUE THREAD

**Issue by AL20** [alexnj/SublimeOnSaveBuild#41]
I want to use SublimeOnSaveBuild to automatically use ng-annotate for a angular project.
I have this error when I save a .js file :

No matching processes belonging to you were found
/bin/sh: node: command not found
[Finished in 0.2s with exit code 127]

Can you help me with this ?

**Comment by alexnj** [comment]
That is likely due to Sublime not being able to locate the node binary, in any of the PATH environment variable locations available to Sublime. You can confirm this by opening Sublime via a command line that already has the correct PATH variable set (and it would work in that case).

Depending on your OS (which you haven't mentioned), you can either export PATH system wide, or change your script to include the path of node binary.

**Comment by alexnj** [comment]
I'm closing this issue since it's not related to the plugin itself, but an issue with your environment configuration. Feel free to continue discussing if you find more trouble in setting it up right here, and I'll help as much as I can.

**Comment by AL20** [comment]
I'll have a closer look at the issue and get back to you if necessary. 
Thanks for quick reply !
